services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGODB_URL=mongodb://db:27017
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
  mongo-backup:
    image: mongo
    command: >
      bash -c "
        echo 'waiting for mongo to start';
        while ! nc -z db 27017; do sleep 1; done;
        mongodump --uri='mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db:27017/?authSource=admin' --out='/backups'";
    depends_on:
      - db
    volumes:
      - ./backups:/backups
volumes:
  mongodb_data:
  backups: